---
geo: 
  version: 0.0.0
  required: false
  requirements: 
    liberty: 
      min: 2.1.4
  description: >
    A simple Liberty Service that any
    package can use to store geographic data
    (latitude, longitude, and above mean sea
    level) for any content.
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html 
  homeable: false
  tables: 
    geo: |
      
      content_id I4 NOTNULL,
      lat F,
      lng F,
      amsl F,
      amsl_unit C(2)
      CONSTRAINT ', CONSTRAINT `geo_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content`( `content_id` )'
      
